plural_noun = input("input a plural noun")
print("Giraffes have aroused the curiousity of " + plural_noun + " since earliest times.")
plural_noun = input("input a plural noun")
part_of_body = input("input a part of the body")
print("The giraffe is the tallest of all living " + plural_noun + ", but scientests are unable to explain how it got its long" + part_of_body)
number = input("input a number")
plural_noun = input("input a plural noun")
part_of_body = input("input a part of the body")
print("The giraffe\'s tremendous height, which might reach " + number + plural_noun + ", comes mostly from its legs and " + part_of_body + ".")
liquid = input("input a type of liquid")
part_of_body = input("input a part of the body")
part_of_body_2 = input("input a part of the body")
print("If a giraffe wants to take a drink of " + liquid + " from the ground, it has to spread its " + part_of_body + " far apart in order to reach down and lap up the water with its huge " + part_of_body_2 + ".")
adjective = input("input an adjective")
plural_noun = input("input a plural noun")
adjective_2 = input("input an adjective")
print("The giraffe has " + adjective + " ears that are sensitive to the faintest " + plural_noun + ", and it has a/an " + adjective_2 + " sense of smell and sight.")
adjective = input("input an adjective")
verb_ing = input("input a verb ending in 'ing'")
noun = input("input a noun")
print("When attacked, a giraffe can put up a/an " + adjective + " fight by " + verb_ing + " out with its hind legs and using its head like a sledge " + noun + ".")
plural_noun = input("input a plural noun")
noun = input("input a noun")
print("Finally, a giraffe can gallop at more than thirty " + plural_noun + " an hour wen pursued and can outrun the fastest " + noun + ".")