plural_noun = input("input a plural noun: ")
plural_noun_2 = input("input a plural noun: ")
part_of_body = input("input a part of the body: ")
number = input("input a number: ")
plural_noun_3 = input("input a plural noun: ")
part_of_body_2 = input("input a part of the body: ")
liquid = input("input a type of liquid: ")
part_of_body_3 = input("input a part of the body: ")
part_of_body_4 = input("input a part of the body: ")
adjective = input("input an adjective: ")
plural_noun_4 = input("input a plural noun: ")
adjective_2 = input("input an adjective: ")
adjective_3 = input("input an adjective: ")
verb_ing = input("input a verb ending in 'ing': ")
noun = input("input a noun: ")
plural_noun_5 = input("input a plural noun: ")
noun_2 = input("input a noun: ")
print("Have I Got a Giraffe for you!")
print("Giraffes have aroused the curiousity of " + plural_noun + " since earliest times.")
print("The giraffe is the tallest of all living " + plural_noun_2 + ", but scientists are unable to explain how it got its long " + part_of_body + ".")
print("The giraffe\'s tremendous height, which might reach " + number + " " + plural_noun_3 + ", comes mostly from its legs and " + part_of_body_2 + ".")
print("If a giraffe wants to take a drink of " + liquid + " from the ground, it has to spread its " + part_of_body_3 + " far apart in order to reach down and lap up the water with its huge " + part_of_body_4 + ".")
print("The giraffe has " + adjective + " ears that are sensitive to the faintest " + plural_noun_4 + ", and it has a/an " + adjective_2 + " sense of smell and sight.")
print("When attacked, a giraffe can put up a/an " + adjective_3 + " fight by " + verb_ing + " out with its hind legs and using its head like a sledge " + noun + ".")
print("Finally, a giraffe can gallop at more than thirty " + plural_noun_5 + " an hour when pursued and can outrun the fastest " + noun_2 + ".")